module.exports = {
  MAX_MESSAGES_PER_USER: 500,
  MESSAGE_ROLES: {
    USER: 'user',
    ASSISTANT: 'assistant',
    OWNER: 'owner',
    SYSTEM: 'system',
  },
  MESSAGE_SOURCES: {
    WHATSAPP: 'whatsapp',
    WEB: 'web',
    ASSISTANT: 'assistant',
    COMMAND: 'command',
    ESCALATION: 'escalation',
    FIREWALL: 'firewall',
  },
  COMMANDS: {
    HELP: '/help',
    PING: '/ping',
    RESET: '/reset',
    SUMMARY: '/summary',
    NOTE: '/note',
    NOTES: '/notes',
    REMIND: '/remind',
    MODEL: '/model',
    TOKENS: '/tokens',
    PROFILE: '/profile',
    ME: '/me',
    CONTACTS: '/contacts',
    PAUSE: '/pause',
    STOP: '/stop',
    START: '/start',
    RESUME: '/resume',
    ASSISTANT: '/assistant',
  },
  ASSISTANT_PAUSE_MS: 5 * 60 * 1000,
  REMINDER_CHECK_CRON: '* * * * *',
  OPENAI_WHISPER_MODEL: process.env.OPENAI_WHISPER_MODEL || 'whisper-1',
  AUDIO_FORMATS: ['flac', 'mp3', 'mp4', 'mpeg', 'mpga', 'm4a', 'ogg', 'wav', 'webm'],
  TMP_DIR: 'tmp',
  UPLOADS_DIR: 'uploads',
  DATA_DIR: 'data',
  DB_FILENAME: 'assistant.db',
  RECONNECT_DELAY_MS: 10000,
  MAX_RECONNECT_ATTEMPTS: 15,
  ERROR_REPLY_COOLDOWN_MS: 120000,
  MAX_REPLY_DELAY_SECONDS: 120,
  MAX_BATCH_DELAY_SECONDS: 300,
  MAX_CONTEXT_WINDOW_MINUTES: 1440,
  IGNORED_MESSAGE_TYPES: [
    'notification_template',
    'e2e_notification',
    'protocol',
    'call_log',
    'gp2',
    'ciphertext',
    'revoked',
    'order',
    'product',
    'unknown',
  ],
};
